version: "3"
services:
  web:
    build: .
    container_name: food_order_web
    entrypoint: /bin/sh
    # command: mix phx.server
    volumes:
      - .:/var/www/food_order
    ports:
      - "4000:4000"
    env_file:
      - .env
    tty: true
    stdin_open: true
